package cpu.core

import chisel3._
import cpu.types.Addressing
import cpu.types.Instruction

/** IFで取得した命令をDecodeしてOFへのOperand取得依頼、ALUで実行する命令の決定を行う...が
 *  命令が可変長で8bit BusでOFで複数回Readが必要なことから IF->ID->OFはpipeline化しない。
 * 
 *  IFがFetchするcycle時点でInstruction, Addressingを決定し、
 *  次cycleでOFが動くか確定するためのI/F提供とする
 */
object InstructionDecode {
  // Opcodeと命令/アドレッシングモードの対応
  val lookupTable: Seq[(UInt, (Instruction.Type, Addressing.Type))] = Seq(
    // binary
    0x69.U -> (Instruction.ADC, Addressing.Immediate),
    0x65.U -> (Instruction.ADC, Addressing.ZeroPage),
    0x75.U -> (Instruction.ADC, Addressing.ZeroPageX),
    0x6d.U -> (Instruction.ADC, Addressing.Absolute),
    0x7d.U -> (Instruction.ADC, Addressing.AbsoluteX),
    0x79.U -> (Instruction.ADC, Addressing.AbsoluteY),
    0x61.U -> (Instruction.ADC, Addressing.IndirectX),
    0x71.U -> (Instruction.ADC, Addressing.IndirectY),
    0xe9.U -> (Instruction.SBC, Addressing.Immediate),
    0xe5.U -> (Instruction.SBC, Addressing.ZeroPage),
    0xf5.U -> (Instruction.SBC, Addressing.ZeroPageX),
    0xed.U -> (Instruction.SBC, Addressing.Absolute),
    0xfd.U -> (Instruction.SBC, Addressing.AbsoluteX),
    0xf9.U -> (Instruction.SBC, Addressing.AbsoluteY),
    0xe1.U -> (Instruction.SBC, Addressing.IndirectX),
    0xf1.U -> (Instruction.SBC, Addressing.IndirectY),
    0x29.U -> (Instruction.AND, Addressing.Immediate),
    0x25.U -> (Instruction.AND, Addressing.ZeroPage),
    0x35.U -> (Instruction.AND, Addressing.ZeroPageX),
    0x2d.U -> (Instruction.AND, Addressing.Absolute),
    0x3d.U -> (Instruction.AND, Addressing.AbsoluteX),
    0x39.U -> (Instruction.AND, Addressing.AbsoluteY),
    0x21.U -> (Instruction.AND, Addressing.IndirectX),
    0x31.U -> (Instruction.AND, Addressing.IndirectY),
    0x49.U -> (Instruction.EOR, Addressing.Immediate),
    0x45.U -> (Instruction.EOR, Addressing.ZeroPage),
    0x55.U -> (Instruction.EOR, Addressing.ZeroPageX),
    0x4d.U -> (Instruction.EOR, Addressing.Absolute),
    0x5d.U -> (Instruction.EOR, Addressing.AbsoluteX),
    0x59.U -> (Instruction.EOR, Addressing.AbsoluteY),
    0x41.U -> (Instruction.EOR, Addressing.IndirectX),
    0x51.U -> (Instruction.EOR, Addressing.IndirectY),
    0x09.U -> (Instruction.ORA, Addressing.Immediate),
    0x05.U -> (Instruction.ORA, Addressing.ZeroPage),
    0x15.U -> (Instruction.ORA, Addressing.ZeroPageX),
    0x0d.U -> (Instruction.ORA, Addressing.Absolute),
    0x1d.U -> (Instruction.ORA, Addressing.AbsoluteX),
    0x19.U -> (Instruction.ORA, Addressing.AbsoluteY),
    0x01.U -> (Instruction.ORA, Addressing.IndirectX),
    0x11.U -> (Instruction.ORA, Addressing.IndirectY),

    // shift, rotate
    0x0a.U -> (Instruction.ASL, Addressing.Accumulator),
    0x06.U -> (Instruction.ASL, Addressing.ZeroPage),
    0x16.U -> (Instruction.ASL, Addressing.ZeroPageX),
    0x0e.U -> (Instruction.ASL, Addressing.Absolute),
    0x1e.U -> (Instruction.ASL, Addressing.AbsoluteX),
    0x4a.U -> (Instruction.LSR, Addressing.Accumulator),
    0x46.U -> (Instruction.LSR, Addressing.ZeroPage),
    0x56.U -> (Instruction.LSR, Addressing.ZeroPageX),
    0x4e.U -> (Instruction.LSR, Addressing.Absolute),
    0x5e.U -> (Instruction.LSR, Addressing.AbsoluteX),
    0x2a.U -> (Instruction.ROL, Addressing.Accumulator),
    0x26.U -> (Instruction.ROL, Addressing.ZeroPage),
    0x36.U -> (Instruction.ROL, Addressing.ZeroPageX),
    0x2e.U -> (Instruction.ROL, Addressing.Absolute),
    0x3e.U -> (Instruction.ROL, Addressing.AbsoluteX),
    0x6a.U -> (Instruction.ROR, Addressing.Accumulator),
    0x66.U -> (Instruction.ROR, Addressing.ZeroPage),
    0x76.U -> (Instruction.ROR, Addressing.ZeroPageX),
    0x6e.U -> (Instruction.ROR, Addressing.Absolute),
    0x7e.U -> (Instruction.ROR, Addressing.AbsoluteX),

    // inc,dec
    0xe6.U -> (Instruction.INC, Addressing.ZeroPage),
    0xf6.U -> (Instruction.INC, Addressing.ZeroPageX),
    0xee.U -> (Instruction.INC, Addressing.Absolute),
    0xfe.U -> (Instruction.INC, Addressing.AbsoluteX),
    0xe8.U -> (Instruction.INX, Addressing.Implied),
    0xc8.U -> (Instruction.INY, Addressing.Implied),
    0xc6.U -> (Instruction.DEC, Addressing.ZeroPage),
    0xd6.U -> (Instruction.DEC, Addressing.ZeroPageX),
    0xce.U -> (Instruction.DEC, Addressing.Absolute),
    0xde.U -> (Instruction.DEC, Addressing.AbsoluteX),
    0xca.U -> (Instruction.DEX, Addressing.Implied),
    0x88.U -> (Instruction.DEY, Addressing.Implied),

    // load/store
    0xa9.U -> (Instruction.LDA, Addressing.Immediate),
    0xa5.U -> (Instruction.LDA, Addressing.ZeroPage),
    0xb5.U -> (Instruction.LDA, Addressing.ZeroPageX),
    0xad.U -> (Instruction.LDA, Addressing.Absolute),
    0xbd.U -> (Instruction.LDA, Addressing.AbsoluteX),
    0xb9.U -> (Instruction.LDA, Addressing.AbsoluteY),
    0xa1.U -> (Instruction.LDA, Addressing.IndirectX),
    0xb1.U -> (Instruction.LDA, Addressing.IndirectY),
    0xa2.U -> (Instruction.LDX, Addressing.Immediate),
    0xa6.U -> (Instruction.LDX, Addressing.ZeroPage),
    0xb6.U -> (Instruction.LDX, Addressing.ZeroPageY),
    0xae.U -> (Instruction.LDX, Addressing.Absolute),
    0xbe.U -> (Instruction.LDX, Addressing.AbsoluteY),
    0xa0.U -> (Instruction.LDY, Addressing.Immediate),
    0xa4.U -> (Instruction.LDY, Addressing.ZeroPage),
    0xb4.U -> (Instruction.LDY, Addressing.ZeroPageX),
    0xac.U -> (Instruction.LDY, Addressing.Absolute),
    0xbc.U -> (Instruction.LDY, Addressing.AbsoluteX),
    0x85.U -> (Instruction.STA, Addressing.ZeroPage),
    0x95.U -> (Instruction.STA, Addressing.ZeroPageX),
    0x8d.U -> (Instruction.STA, Addressing.Absolute),
    0x9d.U -> (Instruction.STA, Addressing.AbsoluteX),
    0x99.U -> (Instruction.STA, Addressing.AbsoluteY),
    0x81.U -> (Instruction.STA, Addressing.IndirectX),
    0x91.U -> (Instruction.STA, Addressing.IndirectY),
    0x86.U -> (Instruction.STX, Addressing.ZeroPage),
    0x96.U -> (Instruction.STX, Addressing.ZeroPageY),
    0x8e.U -> (Instruction.STX, Addressing.Absolute),
    0x84.U -> (Instruction.STY, Addressing.ZeroPage),
    0x94.U -> (Instruction.STY, Addressing.ZeroPageX),
    0x8c.U -> (Instruction.STY, Addressing.Absolute),

    // set,clear
    0x38.U -> (Instruction.SEC, Addressing.Implied),
    0xf8.U -> (Instruction.SED, Addressing.Implied),
    0x78.U -> (Instruction.SEI, Addressing.Implied),
    0x18.U -> (Instruction.CLC, Addressing.Implied),
    0xd8.U -> (Instruction.CLD, Addressing.Implied),
    0x58.U -> (Instruction.CLI, Addressing.Implied),
    0xb8.U -> (Instruction.CLV, Addressing.Implied),

    // compare
    0xc9.U -> (Instruction.CMP, Addressing.Immediate),
    0xc5.U -> (Instruction.CMP, Addressing.ZeroPage),
    0xd5.U -> (Instruction.CMP, Addressing.ZeroPageX),
    0xcd.U -> (Instruction.CMP, Addressing.Absolute),
    0xdd.U -> (Instruction.CMP, Addressing.AbsoluteX),
    0xd9.U -> (Instruction.CMP, Addressing.AbsoluteY),
    0xc1.U -> (Instruction.CMP, Addressing.IndirectX),
    0xd1.U -> (Instruction.CMP, Addressing.IndirectY),
    0xe0.U -> (Instruction.CPX, Addressing.Immediate),
    0xe4.U -> (Instruction.CPX, Addressing.ZeroPage),
    0xec.U -> (Instruction.CPX, Addressing.Absolute),
    0xc0.U -> (Instruction.CPY, Addressing.Immediate),
    0xc4.U -> (Instruction.CPY, Addressing.ZeroPage),
    0xcc.U -> (Instruction.CPY, Addressing.Absolute),

    // jump,return
    0x4c.U -> (Instruction.JMP, Addressing.Absolute),
    0x6c.U -> (Instruction.JMP, Addressing.Indirect),
    0x20.U -> (Instruction.JSR, Addressing.Absolute),
    0x40.U -> (Instruction.RTI, Addressing.Implied),
    0x60.U -> (Instruction.RTS, Addressing.Implied),

    // branch
    0x90.U -> (Instruction.BCC, Addressing.Relative),
    0xb0.U -> (Instruction.BCS, Addressing.Relative),
    0xf0.U -> (Instruction.BEQ, Addressing.Relative),
    0xd0.U -> (Instruction.BNE, Addressing.Relative),
    0x30.U -> (Instruction.BMI, Addressing.Relative),
    0x10.U -> (Instruction.BPL, Addressing.Relative),
    0x50.U -> (Instruction.BVC, Addressing.Relative),
    0x70.U -> (Instruction.BVS, Addressing.Relative),

    // push, pop
    0x48.U -> (Instruction.PHA, Addressing.Implied),
    0x08.U -> (Instruction.PHP, Addressing.Implied),
    0x68.U -> (Instruction.PLA, Addressing.Implied),
    0x28.U -> (Instruction.PLP, Addressing.Implied),

    // data transfer
    0xaa.U -> (Instruction.TAX, Addressing.Implied),
    0xa8.U -> (Instruction.TAY, Addressing.Implied),
    0xba.U -> (Instruction.TSX, Addressing.Implied),
    0x8a.U -> (Instruction.TXA, Addressing.Implied),
    0x9a.U -> (Instruction.TXS, Addressing.Implied),
    0x98.U -> (Instruction.TYA, Addressing.Implied),

    // other
    0x00.U -> (Instruction.BRK, Addressing.Implied),
    0x24.U -> (Instruction.BIT, Addressing.ZeroPage),
    0x2c.U -> (Instruction.BIT, Addressing.Absolute),
    0xea.U -> (Instruction.NOP, Addressing.Implied),

    // undocumented
    0x4b.U -> (Instruction.ALR, Addressing.Immediate),
    0x0b.U -> (Instruction.ANC, Addressing.Immediate),
    0x6b.U -> (Instruction.ARR, Addressing.Immediate),
    0xcb.U -> (Instruction.AXS, Addressing.Immediate),
    0xa3.U -> (Instruction.LAX, Addressing.IndirectX),
    0xa7.U -> (Instruction.LAX, Addressing.ZeroPage),
    0xaf.U -> (Instruction.LAX, Addressing.Absolute),
    0xb3.U -> (Instruction.LAX, Addressing.IndirectY),
    0xb7.U -> (Instruction.LAX, Addressing.ZeroPageY),
    0xbf.U -> (Instruction.LAX, Addressing.AbsoluteY),
    0x83.U -> (Instruction.SAX, Addressing.IndirectX),
    0x87.U -> (Instruction.SAX, Addressing.ZeroPage),
    0x8f.U -> (Instruction.SAX, Addressing.Absolute),
    0x97.U -> (Instruction.SAX, Addressing.ZeroPageY),
    0xc3.U -> (Instruction.DCP, Addressing.IndirectX),
    0xc7.U -> (Instruction.DCP, Addressing.ZeroPage),
    0xcf.U -> (Instruction.DCP, Addressing.Absolute),
    0xd3.U -> (Instruction.DCP, Addressing.IndirectY),
    0xd7.U -> (Instruction.DCP, Addressing.ZeroPageX),
    0xdb.U -> (Instruction.DCP, Addressing.AbsoluteY),
    0xdf.U -> (Instruction.DCP, Addressing.AbsoluteX),
    0xe3.U -> (Instruction.ISC, Addressing.IndirectX),
    0xe7.U -> (Instruction.ISC, Addressing.ZeroPage),
    0xef.U -> (Instruction.ISC, Addressing.Absolute),
    0xf3.U -> (Instruction.ISC, Addressing.IndirectY),
    0xf7.U -> (Instruction.ISC, Addressing.ZeroPageX),
    0xfb.U -> (Instruction.ISC, Addressing.AbsoluteY),
    0xff.U -> (Instruction.ISC, Addressing.AbsoluteX),
    0x23.U -> (Instruction.RLA, Addressing.IndirectX),
    0x27.U -> (Instruction.RLA, Addressing.ZeroPage),
    0x2f.U -> (Instruction.RLA, Addressing.Absolute),
    0x33.U -> (Instruction.RLA, Addressing.IndirectY),
    0x37.U -> (Instruction.RLA, Addressing.ZeroPageX),
    0x3b.U -> (Instruction.RLA, Addressing.AbsoluteY),
    0x3f.U -> (Instruction.RLA, Addressing.AbsoluteX),
    0x63.U -> (Instruction.RRA, Addressing.IndirectX),
    0x67.U -> (Instruction.RRA, Addressing.ZeroPage),
    0x6f.U -> (Instruction.RRA, Addressing.Absolute),
    0x73.U -> (Instruction.RRA, Addressing.IndirectY),
    0x77.U -> (Instruction.RRA, Addressing.ZeroPageX),
    0x7b.U -> (Instruction.RRA, Addressing.AbsoluteY),
    0x7f.U -> (Instruction.RRA, Addressing.AbsoluteX),
    0x03.U -> (Instruction.SLO, Addressing.IndirectX),
    0x07.U -> (Instruction.SLO, Addressing.ZeroPage),
    0x0f.U -> (Instruction.SLO, Addressing.Absolute),
    0x13.U -> (Instruction.SLO, Addressing.IndirectY),
    0x17.U -> (Instruction.SLO, Addressing.ZeroPageX),
    0x1b.U -> (Instruction.SLO, Addressing.AbsoluteY),
    0x1f.U -> (Instruction.SLO, Addressing.AbsoluteX),
    0x43.U -> (Instruction.SRE, Addressing.IndirectX),
    0x47.U -> (Instruction.SRE, Addressing.ZeroPage),
    0x4f.U -> (Instruction.SRE, Addressing.Absolute),
    0x53.U -> (Instruction.SRE, Addressing.IndirectY),
    0x57.U -> (Instruction.SRE, Addressing.ZeroPageX),
    0x5b.U -> (Instruction.SRE, Addressing.AbsoluteY),
    0x5f.U -> (Instruction.SRE, Addressing.AbsoluteX),
    0x80.U -> (Instruction.SKB, Addressing.Immediate),
    0x82.U -> (Instruction.SKB, Addressing.Immediate),
    0x89.U -> (Instruction.SKB, Addressing.Immediate),
    0xc2.U -> (Instruction.SKB, Addressing.Immediate),
    0xe2.U -> (Instruction.SKB, Addressing.Immediate),
    0x0c.U -> (Instruction.IGN, Addressing.Absolute),
    0x1c.U -> (Instruction.IGN, Addressing.AbsoluteX),
    0x3c.U -> (Instruction.IGN, Addressing.AbsoluteX),
    0x5c.U -> (Instruction.IGN, Addressing.AbsoluteX),
    0x7c.U -> (Instruction.IGN, Addressing.AbsoluteX),
    0xdc.U -> (Instruction.IGN, Addressing.AbsoluteX),
    0xfc.U -> (Instruction.IGN, Addressing.AbsoluteX),
    0x04.U -> (Instruction.IGN, Addressing.ZeroPage),
    0x44.U -> (Instruction.IGN, Addressing.ZeroPage),
    0x64.U -> (Instruction.IGN, Addressing.ZeroPage),
    0x14.U -> (Instruction.IGN, Addressing.ZeroPageX),
    0x34.U -> (Instruction.IGN, Addressing.ZeroPageX),
    0x54.U -> (Instruction.IGN, Addressing.ZeroPageX),
    0x74.U -> (Instruction.IGN, Addressing.ZeroPageX),
    0xd4.U -> (Instruction.IGN, Addressing.ZeroPageX),
    0xf4.U -> (Instruction.IGN, Addressing.ZeroPageX),

    // undocumented
    0xeb.U -> (Instruction.SBC, Addressing.Immediate),
    0x1a.U -> (Instruction.NOP, Addressing.Implied),
    0x3a.U -> (Instruction.NOP, Addressing.Implied),
    0x5a.U -> (Instruction.NOP, Addressing.Implied),
    0x7a.U -> (Instruction.NOP, Addressing.Implied),
    0xda.U -> (Instruction.NOP, Addressing.Implied),
    0xfa.U -> (Instruction.NOP, Addressing.Implied)
  )
}
