version: "3"
services:
  test:
   image: hseeberger/scala-sbt:11.0.2-oraclelinux7_1.4.7_2.12.12
   volumes:
     - ./:/work/
   working_dir: /work
   command: sbt test

  generate:
   image: hseeberger/scala-sbt:11.0.2-oraclelinux7_1.4.7_2.12.12
   volumes:
     - ./:/work/
   working_dir: /work
   command: sbt 'run --target-dir dst'

  doc:
   image: hseeberger/scala-sbt:11.0.2-oraclelinux7_1.4.7_2.12.12
   volumes:
     - ./:/work/
   working_dir: /work
   command: sbt doc

  diagram:
    build: 
      context: ./utils/diagrammer/
      dockerfile: Dockerfile
    volumes:
      - ./dst:/diagrammer/dst
    mem_reservation: 4096GB
    environment:
     - "JAVA_OPTS=-XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -XX:MaxRAMFraction=1"
    command: /bin/bash ./diagram.sh -td ./dst -i ./dst/ChiselNes.fir --open-command echo
    

